### PR TITLE
code 'Helping out and getting involved'

### PR DESCRIPTION
**Pull request by jeehmilena**

### CODE REVIEW

**Comment by efeefe** [comment]
We still need the globe, right @jeehmilena ?

**Comment by jeehmilena** [comment]
@efeefe  yes, but the globe will be added in the future because I need to study the code, this code is without the globe but can already be approved, I will send a print of how it was coded here in my local

**Comment by efeefe** [comment]
So for now please add a static image, centered in the USA...

**Comment by jeehmilena** [comment]
Page print with this code but without the globe yet.

screenshot-2018-1-8 subutai

**Comment by jeehmilena** [comment]
@efeefe it's like this, I'm sending a PR for approval

screenshot-2018-1-8 subutai 1

**Pull request merged**
